### ISSUE TITLE
[Feature]: Send attendee confirmation email

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#157]
## TODO

- [x] Investigate email providers
- [x] Figure out costs (if any additional) and relay to Rick
- [x] Figure out solution (PHP vs NextJS)

### Any additional context or links?

Request per Rick: 

> I'm just dropping this here for future registration development - how hard would it be to automate an email to a person after they register?  We say your Paypal receipt is your confirmation but every season I field a couple dozen inquiries about why they haven't gotten a receipt.

**Comment by stanbery** [comment]
No extra cost - using PHP to send emails to R+R already, so adding the receipt feature to the paypal ipn receiver.

**Comment by stanbery** [comment]
Complete
