### ISSUE TITLE
[Feature]: Library scanning functionality

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#26]
## TODO

- [x] Add a 'terminal page'
- [x] Default home screen to terminal page
- [x] Add an API that if a barcode is scanned it says what type it is
- [x] Add test API calls for each type and make sure proper barcode is coming back
- [x] Add test attendees for testing out functionality
- [x] Add a textbox that if scanned tells you what was scanned

## Library scan functionality

- [x] Add functionality that if a user or a library item is scanned in any order
    - [x] Add API functionality for check out (attendee Id, library item id) 
    - [x] Add API functionality for check in (library item id)
    - [x] Add API functionality to not allow a user to check out multiple games
    - [x] A new check out event is created
    - [x] Item checked out should be true on library
    - [x] A list of games checked out and running time should be on scan page
    - [x] A count of games checked out should be on scan page

**Comment by ZinkNotTheMetal** [comment]
Need to be able to handle multiple rows on Play to Win... need to think about when to reset the form (maybe on enter key)

Also need to think about if they scan the person first instead of the game it needs to add that person event

```typescript
model PlayToWinEvents {
  id                         String             @id @default(cuid()) @map(name: "id")
  attendeeId                 Int                @map(name: "attendee_id")
  attendee                   Attendee           @relation(fields: [attendeeId], references: [id])
}
```
