### ISSUE TITLE
[Feature]: Play to Win scanning capability

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#28]
## TODO

- [ ] Need to research PTW rules - https://tngamedays.com/info/Play%20to%20Win%20Rules.pdf

## Play to Win functionality
- [ ] Add functionality that if a user or a play to win item is scanned in any order
    - [ ] User should have a list of games they 'played-to-win'
    - [ ] Should add an event of time that an attendee played the PTW game
