### ISSUE TITLE
[Feature]: Add ability to select which convention for PTW games

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#32]
### New feature you are looking for

Currently play to win games don't have a way to show which convention they are tied to

## TODO:

- [x] Add conventionId to PlayToWinPlay - will help with querying
- [x] Change API to be list by convention (need to figure out default if not passed in?)
- [x] Change UI to accept new list API that passes down the convention
- [x] On page load load all conventions via drop down, on change go get new list
- [x] Table should show games that were stored for that convention
