### ISSUE TITLE
[Feature]: Reporting - Add top 20 games all time checked out

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#42]
## TODO

- [x] Add API to get top 20 games all time (if there are 20, query games that have more than 0 minutes checked out)
- [x] Add JSX component to display game, player count, bgg rating
- [x] Put JSX component in scanning terminal for librarians
