### ISSUE TITLE
[Feature]: Update person information

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#86]
## TODO

- [ ] attendee/{id} - is a new route
- [ ] form that allows an admin to update a person's details
- [ ] should have edit / upsert functionality
- [ ] Should denote if they are a TGD organizer / volunteer
- [ ] Barcode should not be editable

A new attendee page should be created for editing an attendee

### Any additional context or links?

Attendee Table - ln. 201-203
